### ISSUE TITLE
In-contract transfer action, does not have signatures

### ISSUE THREAD

**Issue by jerryfane** [EOSIO/training-EED101#1]
when testing the unstakehash function on local testnet, I get a permission error for the active permission of the contract. 

```
transaction declares authority '{"actor":"hasheseosio","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"hasheseosio","permission":"eosio.code"}], provided keys [], and a delay max limit of 3888000000 ms
```

The code seems to be fine, and I also get the same error when implementing your solution at [lesson end refactored/hasheseosio/](https://github.com/EOSIO/training-EED101/blob/main/hashstorer/hashstorer_6_inline_actions/lesson%20end%20refactored/hasheseosio/hasheseosio.cpp)

I can't understand how to solve this. Please help :)

**Comment by 21jake** [comment]
Same issues here. Could it be a problem related to the EOS Studio?
<img width="495" alt="Screen Shot 2021-07-02 at 14 36 33" src="https://user-images.githubusercontent.com/65590111/124238538-e9193580-db42-11eb-94bd-4969b94bb1ee.png">

**Comment by 21jake** [comment]
I figured out that the contract account has to be given the "eosio.code" permission to perform the inline action.

<code>
cleos set account permission hashstorer active '{"threshold": 1, "keys":[{"key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV", "weight":1}], "accounts":[{"permission":{"actor":"hashstorer","permission":"eosio.code"},"weight":1}] }' owner -p hashstorer
</code>


Make sure to import and unlock your wallet first with <code> cleos wallet import </code> and your private key
